### ISSUE TITLE
Error on refresh

### ISSUE THREAD

**Issue by Its-Alex** [spm-style/webapp#2]
When refresh on the doc get
```javascript
ReferenceError: window is not defined
    at n.ET0q.l.DocumentationInstallComponent.n.ngOnDestroy (/var/data/spm/webapp/dist/server.js:142491:131858)
    at callProviderLifecycles (/var/data/spm/webapp/dist/server.js:13634:18)
    at callElementProvidersLifecycles (/var/data/spm/webapp/dist/server.js:13599:13)
    at callLifecycleHooksChildrenFirst (/var/data/spm/webapp/dist/server.js:13583:17)
    at destroyView (/var/data/spm/webapp/dist/server.js:14927:5)
    at callViewAction (/var/data/spm/webapp/dist/server.js:15078:13)
    at execEmbeddedViewsAction (/var/data/spm/webapp/dist/server.js:15016:17)
    at destroyView (/var/data/spm/webapp/dist/server.js:14925:5)
    at callViewAction (/var/data/spm/webapp/dist/server.js:15078:13)
    at execComponentViewsAction (/var/data/spm/webapp/dist/server.js:14990:13)
```

**Comment by ScandalousMan** [comment]
Hi Alex,

Thanks for the issue.

We fixed it in last release.
Have a good day!
